/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.interfaz;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Telefono;
import ec.edu.ups.modelo.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author braya
 */
public class TelefonosporUsuario1 extends javax.swing.JInternalFrame {

    private ControladorTelefono ctrlTelefono;
    private ControladorUsuario ctrlUsuario;

    /**
     * Creates new form TelefonosporUsuario
     */
    public TelefonosporUsuario1(ControladorUsuario ctrlUsuario, ControladorTelefono ctrTelefono) {
        initComponents();
        this.ctrlUsuario = ctrlUsuario;
        this.ctrlTelefono = ctrTelefono;
    }

    public void tablaTelefonos(List<Telefono> telefonosUs) {
        DefaultTableModel modelo = (DefaultTableModel) tablaTelefonosUsuario.getModel();
        modelo.setRowCount(0);
        for (Telefono telefono : telefonosUs) {
            Object[] telf = {telefono.getCodigo(), telefono.getNumero(), telefono.getTipo(), telefono.getOperadora()};
            modelo.addRow(telf);
        }
        tablaTelefonosUsuario.setModel(modelo);
    }

    public void limpiar() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cedulaLabel = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        apellidoLabel = new javax.swing.JLabel();
        correoLabel = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTelefonosUsuario = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        rBtnCedula = new javax.swing.JRadioButton();
        rBtnCorreo = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        cedulaLabel.setText("Ingrese cedula");

        txtNombre.setEditable(false);
        txtNombre.setBackground(new java.awt.Color(204, 204, 204));

        nombreLabel.setText("Nombre");

        apellidoLabel.setText("Apellido");

        correoLabel.setText("Correo");

        txtApellido.setEditable(false);
        txtApellido.setBackground(new java.awt.Color(204, 204, 204));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        tablaTelefonosUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Numero", "Tipo", "Operadora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaTelefonosUsuario);

        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        rBtnCedula.setText("Buscar por cedula");
        rBtnCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCedulaActionPerformed(evt);
            }
        });

        rBtnCorreo.setText("Buscar por correo");
        rBtnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnCorreoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rBtnCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnCedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaLabel)
                            .addComponent(nombreLabel)
                            .addComponent(apellidoLabel)
                            .addComponent(correoLabel))
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCorreo)
                            .addComponent(txtNombre)
                            .addComponent(txtApellido)
                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                        .addGap(84, 84, 84))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(91, 91, 91)
                        .addComponent(btnListar)
                        .addGap(68, 68, 68)
                        .addComponent(btnAtras)
                        .addContainerGap(137, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(rBtnCedula))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cedulaLabel)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreLabel)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoLabel)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correoLabel)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(rBtnCorreo))
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnListar)
                    .addComponent(btnAtras))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String cedula = txtCedula.getText();
        String correo = txtCorreo.getText();
        System.out.println("cedula a buscar + " + cedula);
        System.out.println("cedula sesion in + " + ctrlUsuario.read(cedula));
        if (rBtnCedula.isSelected()) {
            if (!cedula.isBlank()) {
                var buscarUs = ctrlUsuario.read(cedula);
                if (buscarUs != null) {
                    txtNombre.setText(buscarUs.getNombre());
                    txtApellido.setText(buscarUs.getApellido());
                    txtCorreo.setText(buscarUs.getCorreo());

                    var telefonosUsuario = buscarUs.getListaTelefonos();
                    if (!telefonosUsuario.isEmpty()) {
                        tablaTelefonos(telefonosUsuario);
                    } else {
                        JOptionPane.showMessageDialog(this, "Este usuario no tiene telefonos agregados");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Este usuario no existe");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Ingrese datos para buscar usuario");
            }
        } else {
            if (!correo.isBlank()) {
                var buscarUs = ctrlUsuario.readCorreo(correo);
                if (buscarUs != null) {
                    txtCedula.setText(buscarUs.getCedula());
                    txtNombre.setText(buscarUs.getNombre());
                    txtApellido.setText(buscarUs.getApellido());
                    txtCorreo.setText(buscarUs.getCorreo());

                    var telefonosUsuario = buscarUs.getListaTelefonos();
                    if (!telefonosUsuario.isEmpty()) {
                        tablaTelefonos(telefonosUsuario);
                    } else {
                        JOptionPane.showMessageDialog(this, "Este usuario no tiene telefonos agregados");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Este usuario no existe");
                }
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        limpiar();

//        List<Telefono> telefonos = ctrl.listarTodosTelefonos();
        DefaultTableModel modelo = (DefaultTableModel) tablaTelefonosUsuario.getModel();
        modelo.setRowCount(0);
        
        for (int i = 0; i < ctrlTelefono.findAll().size(); i++) {
            Telefono telf = ctrlTelefono.getListaObjetos().get(i);
            Object[] rowData = {telf.getCodigo(), telf.getNumero(), telf.getTipo(), telf.getOperadora()};
            modelo.addRow(rowData);
        }
        tablaTelefonosUsuario.setModel(modelo);
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        limpiar();
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void rBtnCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCedulaActionPerformed
        // TODO add your handling code here:
        rBtnCedula.setSelected(true);
        rBtnCorreo.setSelected(false);
        txtCorreo.setEnabled(false);
        txtCedula.setEnabled(true);
        limpiar();
    }//GEN-LAST:event_rBtnCedulaActionPerformed

    private void rBtnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnCorreoActionPerformed
        // TODO add your handling code here:
        rBtnCedula.setSelected(false);
        rBtnCorreo.setSelected(true);
        txtCorreo.setEnabled(true);
        txtCedula.setEnabled(false);
        txtNombre.setText("");
        limpiar();
    }//GEN-LAST:event_rBtnCorreoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        limpiar();
        rBtnCedula.setSelected(true);
        rBtnCorreo.setSelected(false);
        txtCorreo.setEnabled(false);
        txtCedula.setEnabled(true);
        txtNombre.setText("");
    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JRadioButton rBtnCedula;
    private javax.swing.JRadioButton rBtnCorreo;
    private javax.swing.JTable tablaTelefonosUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
