/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.interfaz;

import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.modelo.Usuario;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author braya
 */
public class VentanaIniciarSesion extends javax.swing.JInternalFrame {

    private ControladorUsuario ctrlUser;
    private VentanaPrincipal ventanaPrincipal;
    private Usuario usuario;

    /**
     * Creates new form VentanaIniciarSesion
     */
    public VentanaIniciarSesion(ControladorUsuario ctrlUsuario, VentanaPrincipal ventanaPrincipal) {
        initComponents();
        this.ctrlUser = ctrlUsuario;
        this.ventanaPrincipal = ventanaPrincipal;
        //this.ventanaPrincipal = ventanaPrincipal;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public void setTxtCorreo(JTextField txtCorreo) {
        this.txtCorreo = txtCorreo;
    }
    
    public JButton getBtnInicarSesion() {
        return btnInicarSesion;
    }

    public JLabel getIngreseContraseñaL() {
        return ingreseContraseñaL;
    }

    public JLabel getIngreseCorreoL() {
        return ingreseCorreoL;
    }

    public void limpiar() {
        txtCorreo.setText("");
        txtContraseña.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingreseCorreoL = new javax.swing.JLabel();
        ingreseContraseñaL = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnInicarSesion = new javax.swing.JButton();

        setClosable(true);

        ingreseCorreoL.setText("Ingrese Correo");

        ingreseContraseñaL.setText("Ingrese Contraseña");

        btnInicarSesion.setText("Iniciar Sesion");
        btnInicarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingreseCorreoL)
                    .addComponent(ingreseContraseñaL))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicarSesion)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingreseCorreoL)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingreseContraseñaL)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(btnInicarSesion)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicarSesionActionPerformed
        String correo = txtCorreo.getText();
        String contraseña = txtContraseña.getText();

        if (correo.equals("") || contraseña.equals("")) {
            JOptionPane.showMessageDialog(this, "Campos incompletos");
            limpiar();
        } else {
            if (ctrlUser.login(txtCorreo.getText(), txtContraseña.getText())) {
                setTxtCorreo(txtCorreo);
                ventanaPrincipal.getMenuItemIniciarSesion().setVisible(false);
                ventanaPrincipal.getMenuItemRegistar().setVisible(false);
                ventanaPrincipal.getMenuItemCerrar().setVisible(true);
                ventanaPrincipal.getMenuAgenda().setVisible(true);
                this.hide();
                JOptionPane.showMessageDialog(this, "Datos correctos");
            } else {
                JOptionPane.showMessageDialog(this, "Correo o contraseña Incorrectos");
                limpiar();
            }
        }
    }//GEN-LAST:event_btnInicarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicarSesion;
    private javax.swing.JLabel ingreseContraseñaL;
    private javax.swing.JLabel ingreseCorreoL;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
